tolstoyfafa/assos_suite

- .github/workflows/slack-notify.yml
> Add a slack bot to notify on push 

- .github/ISSUE_TEMPLATE/bugfix
- CONTRIBUTING.md
- README.md
> WIP: Feature branch dev #4 opensource

- CONTRIBUTING.md
> Improve contributing file

- backend/pom.xml
- backend/src/main/java/com/motus/assosuite/config/SecurityConfiguration.java
> Feature master 24 authentication security

- .github/workflows/backend-ci.yml
> :construction_worker: Add backend unit test job

- backend/Dockerfile
> :whale: add dockerfile for backend*

- backend/src/main/resources/application.properties
- docker-compose.yml
> :whale: add dockercompose to production purpose

- backend/src/main/java/com/motus/assosuite/repository/AdherentRepository.java
- backend/src/main/java/com/motus/assosuite/rest/AdherentRestController.java
- backend/src/main/java/com/motus/assosuite/rest/impl/AdherentRestControllerImpl.java
- backend/src/main/java/com/motus/assosuite/service/AdherentService.java
- backend/src/main/java/com/motus/assosuite/service/impl/AdherentServiceImpl.java
> :sparkles: Add layers for handle adherents

- backend/pom.xml
- backend/src/main/java/com/motus/assosuite/models/Adherent.java
- backend/src/main/java/com/motus/assosuite/repository/AdherentRepository.java
- backend/src/main/java/com/motus/assosuite/rest/impl/AdherentRestControllerImpl.java
- backend/src/main/java/com/motus/assosuite/service/AdherentService.java
- backend/src/main/java/com/motus/assosuite/service/impl/AdherentServiceImpl.java
- backend/src/main/resources/application-dev.properties
- backend/src/main/resources/application.properties
> Feature master 69 add addhrent

- backend/pom.xml
- backend/src/test/java/com/motus/assosuite/config/MongoConfigTests.java
- backend/src/test/java/com/motus/assosuite/repository/AdherentRepositoryImplTest.java
Resolve: #74 
@MarOuanEElHiTaRY
> Feature adherent repository test

- backend/src/main/java/com/motus/assosuite/config/ServiceContext.java
- backend/src/main/java/com/motus/assosuite/enums/RoleType.java
- backend/src/main/java/com/motus/assosuite/models/Admin.java
- backend/src/main/java/com/motus/assosuite/repository/AdminRepository.java
- backend/src/main/java/com/motus/assosuite/service/AdminService.java
- backend/src/main/java/com/motus/assosuite/service/impl/AdminServiceImpl.java
- backend/src/test/java/com/motus/assosuite/repository/AdminRepositoryImplTest.java
> Feature 12 authentication pojo

- backend/pom.xml
- backend/src/main/java/com/motus/assosuite/models/Adherent.java
- backend/src/main/java/com/motus/assosuite/repository/AdherentRepository.java
- backend/src/main/java/com/motus/assosuite/rest/AdherentRestController.java
- backend/src/main/java/com/motus/assosuite/rest/impl/AdherentRestControllerImpl.java
- backend/src/main/java/com/motus/assosuite/service/AdherentService.java
- backend/src/main/java/com/motus/assosuite/service/impl/AdherentServiceImpl.java
Resolve: #13 
@MarOuanEElHiTaRY
> Feature adhrents stack

- backend/src/main/java/com/motus/assosuite/models/Adherent.java
- backend/src/main/java/com/motus/assosuite/rest/AdherentRestController.java
- backend/src/main/java/com/motus/assosuite/rest/impl/AdherentRestControllerImpl.java
> Feature master 85 response

- frontend/package.json
- frontend/public/index.html
- frontend/public/manifest.json
- frontend/src/index.js
- frontend/yarn.lock
> :heavy_plus_sign: add redux

- frontend/.env
- frontend/package.json
- frontend/public/index.html
- frontend/src/App.js
- frontend/src/Login/Login.js
- frontend/yarn.lock
> Feature 94 ui admi auth

- backend/src/main/java/com/motus/assosuite/models/Adherent.java
- backend/src/main/java/com/motus/assosuite/rest/AdherentRestController.java
- backend/src/main/java/com/motus/assosuite/rest/impl/AdherentRestControllerImpl.java
- backend/src/main/java/com/motus/assosuite/service/AdherentService.java
- backend/src/main/java/com/motus/assosuite/service/impl/AdherentServiceImpl.java
- frontend/.env-sample
- frontend/package.json
- frontend/yarn.lock
> Feature master 94 authen front

- backend/src/main/java/com/motus/assosuite/config/SecurityConfiguration.java
> :sparkles: [BACK] Add cors origin

- backend/pom.xml
- backend/src/main/java/com/motus/assosuite/config/SwaggerConfiguration.java
- backend/src/main/java/com/motus/assosuite/rest/impl/AuthenticationRestControllerImpl.java
> :sparkles: [BACK] Add swagger

- backend/src/main/java/com/motus/assosuite/api/exceptions/ExceptionMapper.java
- backend/src/main/java/com/motus/assosuite/api/exceptions/JwtEntryPoint.java
- backend/src/main/java/com/motus/assosuite/config/SecurityConfiguration.java
> :sparkles: [BACK] Add JwtEntryPOint to handle authe exceptions

- backend/src/main/java/com/motus/assosuite/rest/AdherentRestController.java
- backend/src/main/java/com/motus/assosuite/rest/impl/AdherentRestControllerImpl.java
- backend/src/main/java/com/motus/assosuite/service/AdherentService.java
- backend/src/main/java/com/motus/assosuite/service/impl/AdherentServiceImpl.java
- backend/src/test/java/com/motus/assosuite/repository/AdherentRepositoryImplTest.java
> Feature master #105

- backend/src/main/java/com/motus/assosuite/rest/AdherentRestController.java
- backend/src/main/java/com/motus/assosuite/rest/impl/AdherentRestControllerImpl.java
- backend/src/main/java/com/motus/assosuite/service/AdherentService.java
- backend/src/main/java/com/motus/assosuite/service/impl/AdherentServiceImpl.java
> :sparkles: [BACK] Add sorting to list adhrents

- frontend/package.json
- frontend/src/App.js
- frontend/src/authProvider.js
- frontend/src/constants.js
- frontend/src/dataProvider.js
- frontend/src/index.js
- frontend/yarn.lock
> Feature master 94 ui admin

- frontend/src/AdherentList.js
- frontend/src/App.js
- frontend/src/Login/Login.js
- frontend/src/authorization.js
- frontend/src/dataProvider.js
> V1 dev data provider bind

- frontend/src/AdherentCreate.js
- frontend/src/AdherentList.js
- frontend/src/App.js
> :spreakless: [FRONT] Add create adherent view

- backend/src/main/java/com/motus/assosuite/service/impl/AdherentServiceImpl.java
- frontend/src/AdherentCreate.js
- frontend/src/AdherentEdit.js
- frontend/src/App.js
> V1 dev #117 feature edit adhrenet view

- frontend/src/AdhrentShow.js
- frontend/src/App.js
> :sprakles: [FRONT] Add show adherent view

- backend/pom.xml
- backend/src/main/java/com/motus/assosuite/service/MailService.java
- backend/src/main/java/com/motus/assosuite/service/impl/AdherentServiceImpl.java
- backend/src/main/java/com/motus/assosuite/service/impl/MailServiceImpl.java
- backend/src/main/resources/application-dev.properties
- backend/src/main/resources/application.properties
> V1 dev #122 gmail smtp

- docker-compose.yml
> :whale: Enhance the docker compose file

- frontend/package.json
- frontend/src/App.js
- frontend/yarn.lock
Resolve: #127 
Thank you for your contribution
> V1 dev #127 translate

- backend/Dockerfile-prod
- docker-compose-prod.yml
- frontend/Dockerfile-prod
> :whale: Add docker production mode files

- .github/workflows/publish.yml
- README.md
- backend/Dockerfile-prod
- backend/src/main/resources/application-prod.properties
- backend/src/main/resources/application.properties
- docker-compose-prod.yml
- docker-compose.yml
- docker-compose.yml-sample
- frontend/.env.development
- frontend/.env.production
- frontend/Dockerfile-prod
- frontend/src/constants.js
> :whale: Add workflow to publish new docker images

- backend/Dockerfile-prod
- backend/src/main/resources/application.properties
> V1 dev #57

- docker-compose-prod.yml
> :whale: Avoid display nginx version on header

- .gitignore
- README.md
- config/postfix-accounts.cf
- config/setup.sh
- docker-compose.yml
> Master #161 update readme

- frontend/package.json
- frontend/public/manifest.json
- frontend/src/App.js
- frontend/src/configuration/Configuration.js
- frontend/src/layout/CustomAppBar.js
- frontend/src/layout/Layout.js
- frontend/src/routes.js
- frontend/yarn.lock
> Feature master #143 change pwd

- docker-compose.yml
> :bug: :whale: fix Docker frontend image

- backend/src/main/java/com/motus/assosuite/service/impl/MailServiceImpl.java
> :bug: [BACK] fix mail content

- .github/workflows/publish.yml
- README.md
- backend/README.md
- backend/pom.xml
- backend/src/main/resources/application-dev.properties
- backend/src/main/resources/application.properties
- docker-compose-prod.yml
- frontend/README.md
- frontend/package.json
> Master feature #172 enhance
